apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.microservice.namespace }}
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: {{ .Values.microservice.name }}
    spec:
      containers:
      - name: {{ .Values.microservice.name }}
        image: {{ .Values.workload.image }}
        envFrom:
          - configMapRef:
              name: {{ .Values.microservice.name }}-config
        resources:
          requests:
            memory: {{ .Values.workload.resources.memory }}
            cpu: {{ .Values.workload.resources.cpu }}
          limits:
            memory: {{ .Values.workload.resources.memory }}
        ports:
          - containerPort: {{ .Values.workload.port }}