microservice: 
  name: grade-submission-portal
  namespace: grade-submission
  replicas: 1

workload:  
  image: mahmoudnasser8080/grade-submission-portal:2.0.0
  port: 5001
  resources:
    memory: "128Mi"
    cpu: "200m"
  livenessDelay: 15

env:  
  GRADE_SERVICE_HOST: grade-submission-api

